<a href="https://colab.research.google.com/github/matiascabrejos/IA-Humai/blob/main/df_airbnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df_airbnb = pd.read_csv('listings.csv')

In [ ]:
df_price = df_airbnb.pivot_table(
    index=['neighbourhood'],
    values=['host_id'],
    aggfunc='count'
)
df_price.sort_values('host_id', ascending=False)

                                        host_id
neighbourhood
Centrum-West                                870
De Baarsjes - Oud-West                      803
Centrum-Oost                                618
De Pijp - Rivierenbuurt                     553
Westerpark                                  371
Zuid                                        366
Oud-Oost                                    313
Oud-Noord                                   251
Bos en Lommer                               248
Oostelijk Havengebied - Indische Buurt      205
IJburg - Zeeburgereiland                    160
Watergraafsmeer                             147
Noord-West                                  136
Slotervaart                                 101
Noord-Oost                                   93
Geuzenveld - Slotermeer                      83
Buitenveldert - Zuidas                       56
De Aker - Nieuw Sloten                       50
Gaasperdam - Driemond                        44
Osdorp                                       36
Bijlmer-Centrum                              33
Bijlmer-Oost                                 19

In [ ]:
df_price_3 = df_airbnb.pivot_table(
    index=['neighbourhood'],
    values=['price'],
    aggfunc='mean'
)
df_price_3.round().sort_values('price', ascending=False)

                                        price
neighbourhood
Centrum-Oost                            203.0
Zuid                                    187.0
Centrum-West                            183.0
Oud-Noord                               180.0
IJburg - Zeeburgereiland                178.0
De Pijp - Rivierenbuurt                 177.0
Bijlmer-Centrum                         169.0
Watergraafsmeer                         165.0
Westerpark                              162.0
De Baarsjes - Oud-West                  161.0
Oud-Oost                                156.0
De Aker - Nieuw Sloten                  144.0
Oostelijk Havengebied - Indische Buurt  142.0
Noord-Oost                              139.0
Bos en Lommer                           137.0
Noord-West                              129.0
Bijlmer-Oost                            128.0
Geuzenveld - Slotermeer                 127.0
Buitenveldert - Zuidas                  127.0
Osdorp                                  124.0
Slotervaart                             111.0
Gaasperdam - Driemond                    98.0

In [15]:
df_group = df_airbnb.groupby('neighbourhood').aggregate({
                                        'price':['mean','median','size']})
df_group.round()

                                        price
                                         mean median size
neighbourhood
Bijlmer-Centrum                         169.0  110.0   33
Bijlmer-Oost                            128.0   90.0   19
Bos en Lommer                           137.0  122.0  248
Buitenveldert - Zuidas                  127.0  102.0   56
Centrum-Oost                            203.0  150.0  618
Centrum-West                            183.0  150.0  870
De Aker - Nieuw Sloten                  144.0   94.0   50
De Baarsjes - Oud-West                  161.0  140.0  803
De Pijp - Rivierenbuurt                 177.0  150.0  553
Gaasperdam - Driemond                    98.0   85.0   44
Geuzenveld - Slotermeer                 127.0  112.0   83
IJburg - Zeeburgereiland                178.0  142.0  160
Noord-Oost                              139.0  117.0   93
Noord-West                              129.0  122.0  136
Oostelijk Havengebied - Indische Buurt  142.0  125.0  205
Osdorp                                  124.0  100.0   36
Oud-Noord                               180.0  129.0  251
Oud-Oost                                156.0  140.0  313
Slotervaart                             111.0   99.0  101
Watergraafsmeer                         165.0  150.0  147
Westerpark                              162.0  135.0  371
Zuid                                    187.0  150.0  366

In [ ]:
df_price_2 = df_airbnb.pivot_table(
    index=['neighbourhood', 'name', 'room_type'],
).reset_index()
df_price_2

,neighbourhood,name,room_type,availability_365,calculated_host_listings_count,host_id,id,latitude,longitude,minimum_nights,number_of_reviews,number_of_reviews_ltm,price,reviews_per_month
0,Bijlmer-Centrum,4 bed condo close to Johan Cruijff Arena/Ziggo...,Entire home/apt,218.0,1.0,329090026.0,52849391.0,52.324930,4.939620,1.0,0.0,0.0,96.0,NaN
1,Bijlmer-Centrum,"A'dam Good Story, Modern Minimalistic Studio",Entire home/apt,69.0,1.0,7019438.0,16459632.0,52.315620,4.953120,3.0,183.0,12.0,95.0,3.38
2,Bijlmer-Centrum,Apartment with huge garden in Amsterdam,Entire home/apt,0.0,1.0,27776233.0,26147088.0,52.320610,4.943730,7.0,3.0,0.0,99.0,0.08
3,Bijlmer-Centrum,B&B Calypso Amsterdam,Private room,329.0,1.0,6300541.0,1149380.0,52.317740,4.946470,1.0,408.0,17.0,46.0,4.16
4,Bijlmer-Centrum,Beautiful apartment with garden 10 min from city,Entire home/apt,283.0,1.0,431848110.0,53337788.0,52.326410,4.948760,17.0,0.0,0.0,80.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5501,Zuid,cozy apartment old south // great location,Entire home/apt,12.0,1.0,22473934.0,34559989.0,52.352470,4.855370,2.0,7.0,3.0,160.0,5.83
5502,Zuid,souterrain kamers met ontbijtruimte vondelpark,Private room,0.0,1.0,25681294.0,28973269.0,52.353400,4.865340,3.0,23.0,0.0,129.0,0.60
5503,Zuid,★ UNIQUE & COMFORTABLE APT | CENTER OF AMSTERD...,Private room,0.0,6.0,46691672.0,42368920.0,52.360650,4.874640,3.0,4.0,0.0,175.0,0.24
5504,Zuid,★★★★★ NEW: LUXURIOUS | SPACIOUS | TERRACE ★★★★★,Entire home/apt,0.0,1.0,248908697.0,52650916.0,52.345400,4.860110,3.0,2.0,2.0,175.0,1.67
5505,Zuid,☆ spacious Apt @Vondelpark w balcony and garden ☆,Entire home/apt,0.0,1.0,2346326.0,11962960.0,52.348694,4.856783,9.0,28.0,2.0,159.0,0.63